-- ============================================================================
-- SQL BUSINESS QUESTIONS — 37 working queries
-- Netflix Customer Intelligence, Churn Prediction & AI Analytics Copilot
-- Tier A: Intermediate (01-15) | Tier B: Advanced (16-27) | Tier C: Expert (28-37)
-- Tested against the loaded PostgreSQL database (netflix).
-- ============================================================================

-- ============================================================================
-- SECTION A — INTERMEDIATE (15) · Joins, aggregation, group-by reporting
-- ============================================================================

-- 01. How many active customers does the platform currently have, by country?
SELECT c.country,
       COUNT(DISTINCT s.customer_id) AS active_customers
FROM customers c
JOIN subscriptions s ON s.customer_id = c.customer_id
WHERE s.subscription_status = 'Active'
GROUP BY c.country
ORDER BY active_customers DESC;

-- 02. What is the total and average monthly revenue generated by each plan?
SELECT p.plan_name,
       SUM(s.monthly_price) AS total_monthly_revenue,
       AVG(s.monthly_price) AS avg_monthly_revenue
FROM subscriptions s
JOIN subscription_plans p ON p.plan_id = s.plan_id
WHERE s.subscription_status = 'Active'
GROUP BY p.plan_name
ORDER BY total_monthly_revenue DESC;

-- 03. What is the overall churn rate (percentage of customers with churned=true)?
SELECT ROUND(100.0 * SUM(churned::int) / COUNT(*), 2) AS churn_rate_pct
FROM churn_labels;

-- 04. Which acquisition channel brought in the most customers, and the churn rate per channel?
SELECT c.acquisition_channel,
       COUNT(DISTINCT c.customer_id) AS customers,
       ROUND(100.0 * SUM(cl.churned::int) / COUNT(*), 2) AS churn_rate_pct
FROM customers c
LEFT JOIN churn_labels cl ON cl.customer_id = c.customer_id
GROUP BY c.acquisition_channel
ORDER BY customers DESC;

-- 05. What is the average customer age by subscription plan?
SELECT p.plan_name,
       ROUND(AVG(c.age), 1) AS avg_age
FROM customers c
JOIN subscriptions s ON s.customer_id = c.customer_id
JOIN subscription_plans p ON p.plan_id = s.plan_id
WHERE s.subscription_status = 'Active'
GROUP BY p.plan_name
ORDER BY avg_age;

-- 06. List the top 10 most-watched titles by total watch_duration_minutes.
SELECT ct.title,
       SUM(va.watch_duration_minutes) AS total_watch_minutes
FROM viewing_activity va
JOIN content ct ON ct.content_id = va.content_id
GROUP BY ct.title
ORDER BY total_watch_minutes DESC
LIMIT 10;

-- 07. What is the average completion_percentage by content_type and genre?
SELECT ct.content_type,
       ct.genre,
       ROUND(AVG(va.completion_percentage), 2) AS avg_completion_pct
FROM viewing_activity va
JOIN content ct ON ct.content_id = va.content_id
GROUP BY ct.content_type, ct.genre
ORDER BY ct.content_type, ct.genre;

-- 08. How many failed payments occurred in each of the last 12 months?
SELECT TO_CHAR(DATE_TRUNC('month', payment_date), 'YYYY-MM') AS month,
       COUNT(*) AS failed_payments
FROM payments
WHERE payment_status = 'Failed'
  AND payment_date >= DATE_TRUNC('month', CURRENT_DATE) - INTERVAL '12 months'
GROUP BY DATE_TRUNC('month', payment_date)
ORDER BY month;

-- 09. What is the average resolution_time_hours by issue_category?
SELECT issue_category,
       ROUND(AVG(resolution_time_hours), 2) AS avg_resolution_hours,
       COUNT(*) AS tickets
FROM support_tickets
WHERE resolution_time_hours IS NOT NULL
GROUP BY issue_category
ORDER BY avg_resolution_hours DESC;

-- 10. Distribution of customer_satisfaction_score across resolved/closed tickets.
SELECT customer_satisfaction_score,
       COUNT(*) AS ticket_count
FROM support_tickets
WHERE ticket_status IN ('Resolved', 'Closed')
  AND customer_satisfaction_score IS NOT NULL
GROUP BY customer_satisfaction_score
ORDER BY customer_satisfaction_score;

-- 11. Which device_type generates the most total viewing minutes?
SELECT device_type,
       SUM(watch_duration_minutes) AS total_minutes
FROM viewing_activity
GROUP BY device_type
ORDER BY total_minutes DESC;

-- 12. What is the average rating from customer_feedback, grouped by sentiment_label?
SELECT sentiment_label,
       ROUND(AVG(rating), 2) AS avg_rating,
       COUNT(*) AS n
FROM customer_feedback
GROUP BY sentiment_label
ORDER BY avg_rating DESC;

-- 13. How many customers signed up through each channel in each calendar year?
SELECT EXTRACT(YEAR FROM registration_date)::int AS signup_year,
       acquisition_channel,
       COUNT(*) AS customers
FROM customers
GROUP BY signup_year, acquisition_channel
ORDER BY signup_year, customers DESC;

-- 14. What percentage of customers have auto_renew turned off?
SELECT ROUND(100.0 * COUNT(DISTINCT CASE WHEN auto_renew = FALSE THEN customer_id END)
             / COUNT(DISTINCT customer_id), 2) AS pct_auto_renew_off
FROM subscriptions;

-- 15. List all customers who raised more than 3 support tickets + total count.
SELECT customer_id,
       COUNT(*) AS ticket_count
FROM support_tickets
GROUP BY customer_id
HAVING COUNT(*) > 3
ORDER BY ticket_count DESC;

-- ============================================================================
-- SECTION B — ADVANCED (12) · CTEs, window functions, cohort-style analysis
-- ============================================================================

-- 16. Using RANK(), rank plans by total revenue (monthly_price x active count).
SELECT p.plan_id,
       p.plan_name,
       p.monthly_price,
       COUNT(*) AS active_subs,
       p.monthly_price * COUNT(*) AS total_revenue,
       RANK() OVER (ORDER BY p.monthly_price * COUNT(*) DESC) AS revenue_rank
FROM subscriptions s
JOIN subscription_plans p USING (plan_id)
WHERE subscription_status = 'Active'
GROUP BY p.plan_id, p.plan_name, p.monthly_price
ORDER BY revenue_rank;

-- 17. Using ROW_NUMBER(), identify each customer's most recent support ticket.
WITH ranked AS (
    SELECT *,
           ROW_NUMBER() OVER (PARTITION BY customer_id
                              ORDER BY ticket_date DESC, ticket_id DESC) AS rn
    FROM support_tickets
)
SELECT ticket_id, customer_id, ticket_date, issue_category, ticket_status
FROM ranked
WHERE rn = 1;

-- 18. 3-month moving average of new customer registrations (window function).
WITH monthly AS (
    SELECT DATE_TRUNC('month', registration_date)::date AS month,
           COUNT(*) AS new_customers
    FROM customers
    GROUP BY 1
)
SELECT month,
       new_customers,
       ROUND(AVG(new_customers) OVER (ORDER BY month
              ROWS BETWEEN 2 PRECEDING AND CURRENT ROW), 2) AS moving_avg_3m
FROM monthly
ORDER BY month;

-- 19. Using LAG(), customers whose most recent month watch time < prior month.
WITH monthly_watch AS (
    SELECT customer_id,
           DATE_TRUNC('month', viewing_date)::date AS month,
           SUM(watch_duration_minutes) AS watch_minutes
    FROM viewing_activity
    GROUP BY 1, 2
),
with_lag AS (
    SELECT *,
           LAG(watch_minutes) OVER (PARTITION BY customer_id ORDER BY month) AS prev_minutes
    FROM monthly_watch
)
SELECT customer_id, month, watch_minutes, prev_minutes
FROM with_lag
WHERE prev_minutes IS NOT NULL AND watch_minutes < prev_minutes;

-- 20. Cohort retention: % of each registration-month cohort still active at 1, 3, 6 months.
WITH cohorts AS (
    SELECT customer_id,
           DATE_TRUNC('month', registration_date)::date AS cohort_month
    FROM customers
),
subs AS (
    SELECT customer_id,
           subscription_start_date,
           COALESCE(subscription_end_date, '9999-12-31'::date) AS end_date
    FROM subscriptions
)
SELECT c.cohort_month,
       COUNT(DISTINCT c.customer_id) AS cohort_size,
       ROUND(100.0 * COUNT(DISTINCT CASE WHEN EXISTS (
               SELECT 1 FROM subs s
               WHERE s.customer_id = c.customer_id
                 AND s.subscription_start_date <= c.cohort_month + INTERVAL '1 month'
                 AND s.end_date > c.cohort_month + INTERVAL '1 month')
             THEN c.customer_id END) / COUNT(DISTINCT c.customer_id), 1) AS retained_1m,
       ROUND(100.0 * COUNT(DISTINCT CASE WHEN EXISTS (
               SELECT 1 FROM subs s
               WHERE s.customer_id = c.customer_id
                 AND s.subscription_start_date <= c.cohort_month + INTERVAL '3 months'
                 AND s.end_date > c.cohort_month + INTERVAL '3 months')
             THEN c.customer_id END) / COUNT(DISTINCT c.customer_id), 1) AS retained_3m,
       ROUND(100.0 * COUNT(DISTINCT CASE WHEN EXISTS (
               SELECT 1 FROM subs s
               WHERE s.customer_id = c.customer_id
                 AND s.subscription_start_date <= c.cohort_month + INTERVAL '6 months'
                 AND s.end_date > c.cohort_month + INTERVAL '6 months')
             THEN c.customer_id END) / COUNT(DISTINCT c.customer_id), 1) AS retained_6m
FROM cohorts c
GROUP BY c.cohort_month
ORDER BY c.cohort_month;

-- 21. Using DENSE_RANK(), top 5 countries by churn rate.
WITH churn AS (
    SELECT c.country,
           COUNT(*) AS customers,
           SUM(cl.churned::int) AS churned
    FROM customers c
    LEFT JOIN churn_labels cl ON cl.customer_id = c.customer_id
    GROUP BY c.country
),
ranked AS (
    SELECT country,
           customers,
           churned,
           ROUND(100.0 * churned / customers, 2) AS churn_rate_pct,
           DENSE_RANK() OVER (ORDER BY 100.0 * churned / customers DESC) AS rnk
    FROM churn
)
SELECT country, customers, churned, churn_rate_pct
FROM ranked
WHERE rnk <= 5
ORDER BY rnk;

-- 22. Running total of payments per customer, ordered by payment_date.
SELECT customer_id,
       payment_date,
       amount,
       SUM(amount) OVER (PARTITION BY customer_id
                         ORDER BY payment_date, payment_id) AS running_total
FROM payments
WHERE payment_status = 'Success'
ORDER BY customer_id, payment_date;

-- 23. Customers whose watch time declined for three consecutive months.
WITH monthly AS (
    SELECT customer_id,
           DATE_TRUNC('month', viewing_date)::date AS month,
           SUM(watch_duration_minutes) AS m
    FROM viewing_activity
    GROUP BY 1, 2
),
lagged AS (
    SELECT *,
           LAG(m) OVER (PARTITION BY customer_id ORDER BY month) AS m1,
           LAG(m, 2) OVER (PARTITION BY customer_id ORDER BY month) AS m2
    FROM monthly
)
SELECT DISTINCT customer_id
FROM lagged
WHERE m < m1 AND m1 < m2;

-- 24. Monthly churn rate over the last 12 months.
WITH months AS (
    SELECT generate_series(DATE_TRUNC('month', CURRENT_DATE) - INTERVAL '11 months',
                           DATE_TRUNC('month', CURRENT_DATE), '1 month')::date AS month
),
churned AS (
    SELECT DATE_TRUNC('month', churn_date)::date AS month,
           COUNT(*) AS churned_count
    FROM churn_labels
    WHERE churn_date IS NOT NULL
    GROUP BY 1
),
active_at_start AS (
    SELECT DATE_TRUNC('month', subscription_start_date)::date AS month,
           COUNT(DISTINCT customer_id) AS active_count
    FROM subscriptions
    WHERE subscription_start_date < DATE_TRUNC('month', CURRENT_DATE)
    GROUP BY 1
)
SELECT m.month,
       COALESCE(ch.churned_count, 0) AS churned,
       COALESCE(a.active_count, 0) AS active_at_start,
       ROUND(100.0 * COALESCE(ch.churned_count, 0) / NULLIF(a.active_count, 0), 2) AS churn_rate_pct
FROM months m
LEFT JOIN churned ch ON ch.month = m.month
LEFT JOIN active_at_start a ON a.month = m.month
ORDER BY m.month;

-- 25. Customer retention rate by acquisition_channel.
SELECT c.acquisition_channel,
       COUNT(DISTINCT c.customer_id) AS acquired,
       COUNT(DISTINCT CASE WHEN s.subscription_status = 'Active' THEN c.customer_id END) AS still_active,
       ROUND(100.0 * COUNT(DISTINCT CASE WHEN s.subscription_status = 'Active' THEN c.customer_id END)
             / COUNT(DISTINCT c.customer_id), 2) AS retention_pct
FROM customers c
LEFT JOIN subscriptions s ON s.customer_id = c.customer_id
GROUP BY c.acquisition_channel
ORDER BY retention_pct DESC;

-- 26. Using a CTE + NTILE(4), rank customers into lifetime-spend quartiles.
WITH spend AS (
    SELECT customer_id,
           SUM(amount) AS lifetime_spend
    FROM payments
    WHERE payment_status = 'Success'
    GROUP BY customer_id
)
SELECT customer_id,
       lifetime_spend,
       NTILE(4) OVER (ORDER BY lifetime_spend) AS spend_quartile
FROM spend
ORDER BY lifetime_spend DESC;

-- 27. Top 3 issue_subcategory by ticket volume per country (CTE + ROW_NUMBER).
WITH base AS (
    SELECT c.country,
           t.issue_subcategory,
           COUNT(*) AS ticket_volume
    FROM support_tickets t
    JOIN customers c ON c.customer_id = t.customer_id
    GROUP BY c.country, t.issue_subcategory
),
ranked AS (
    SELECT *,
           ROW_NUMBER() OVER (PARTITION BY country ORDER BY ticket_volume DESC) AS rn
    FROM base
)
SELECT country, issue_subcategory, ticket_volume
FROM ranked
WHERE rn <= 3
ORDER BY country, rn;

-- ============================================================================
-- SECTION C — EXPERT (10) · Multi-CTE pipelines, business-driven analysis
-- ============================================================================

-- 28. Customers with 2+ failed payments in last 90 days flagged as high churn risk.
WITH failed AS (
    SELECT customer_id,
           COUNT(*) AS failed_payment_count
    FROM payments
    WHERE payment_status = 'Failed'
      AND payment_date >= CURRENT_DATE - INTERVAL '90 days'
    GROUP BY customer_id
    HAVING COUNT(*) >= 2
),
risk AS (
    SELECT customer_id FROM churn_labels WHERE churned = TRUE
)
SELECT f.customer_id,
       f.failed_payment_count,
       s.plan_id AS current_plan
FROM failed f
JOIN risk r ON r.customer_id = f.customer_id
JOIN subscriptions s ON s.customer_id = f.customer_id AND s.subscription_status = 'Active'
ORDER BY f.failed_payment_count DESC;

-- 29. Engagement 30 days before vs after each customer's most recent price change.
WITH price_changes AS (
    SELECT customer_id,
           subscription_start_date AS change_date,
           monthly_price AS new_price,
           LAG(monthly_price) OVER (PARTITION BY customer_id
                                    ORDER BY subscription_start_date) AS old_price
    FROM subscriptions
),
changes AS (
    SELECT customer_id, change_date
    FROM price_changes
    WHERE old_price IS NOT NULL AND new_price <> old_price
)
SELECT ch.customer_id,
       ROUND(AVG(CASE WHEN e.viewing_date BETWEEN ch.change_date - INTERVAL '30 days' AND ch.change_date
                      THEN e.watch_duration_minutes END), 2) AS avg_before,
       ROUND(AVG(CASE WHEN e.viewing_date > ch.change_date
                      AND e.viewing_date <= ch.change_date + INTERVAL '30 days'
                      THEN e.watch_duration_minutes END), 2) AS avg_after,
       ROUND(100.0 * (AVG(CASE WHEN e.viewing_date > ch.change_date
                               AND e.viewing_date <= ch.change_date + INTERVAL '30 days'
                               THEN e.watch_duration_minutes END)
                     - AVG(CASE WHEN e.viewing_date BETWEEN ch.change_date - INTERVAL '30 days' AND ch.change_date
                                 THEN e.watch_duration_minutes END))
             / NULLIF(AVG(CASE WHEN e.viewing_date BETWEEN ch.change_date - INTERVAL '30 days' AND ch.change_date
                               THEN e.watch_duration_minutes END), 0), 2) AS pct_change
FROM changes ch
JOIN viewing_activity e ON e.customer_id = ch.customer_id
GROUP BY ch.customer_id
HAVING AVG(CASE WHEN e.viewing_date BETWEEN ch.change_date - INTERVAL '30 days' AND ch.change_date
                THEN e.watch_duration_minutes END) IS NOT NULL
   AND AVG(CASE WHEN e.viewing_date > ch.change_date
                AND e.viewing_date <= ch.change_date + INTERVAL '30 days'
                THEN e.watch_duration_minutes END) IS NOT NULL;

-- 30. Per-country summary: total, churned, churn rate, avg CLV (churned), top reason.
WITH country_stats AS (
    SELECT c.country,
           COUNT(DISTINCT c.customer_id) AS total_customers,
           COUNT(DISTINCT CASE WHEN cl.churned THEN c.customer_id END) AS churned_customers,
           ROUND(100.0 * COUNT(DISTINCT CASE WHEN cl.churned THEN c.customer_id END)
                 / NULLIF(COUNT(DISTINCT c.customer_id), 0), 2) AS churn_rate_pct
    FROM customers c
    LEFT JOIN churn_labels cl ON cl.customer_id = c.customer_id
    GROUP BY c.country
),
clv AS (
    SELECT c.country,
           AVG(p.amt) AS avg_clv_churned
    FROM customers c
    JOIN churn_labels cl ON cl.customer_id = c.customer_id AND cl.churned
    LEFT JOIN (SELECT customer_id, SUM(amount) AS amt
               FROM payments WHERE payment_status = 'Success' GROUP BY customer_id) p
           ON p.customer_id = c.customer_id
    GROUP BY c.country
),
top_reason AS (
    SELECT c.country,
           cl.churn_reason,
           COUNT(*) AS n,
           ROW_NUMBER() OVER (PARTITION BY c.country ORDER BY COUNT(*) DESC) AS rn
    FROM customers c
    JOIN churn_labels cl ON cl.customer_id = c.customer_id
       AND cl.churned AND cl.churn_reason IS NOT NULL
    GROUP BY c.country, cl.churn_reason
)
SELECT cs.country,
       cs.total_customers,
       cs.churned_customers,
       cs.churn_rate_pct,
       ROUND(clv.avg_clv_churned, 2) AS avg_clv_churned,
       tr.churn_reason AS top_churn_reason
FROM country_stats cs
LEFT JOIN clv ON clv.country = cs.country
LEFT JOIN top_reason tr ON tr.country = cs.country AND tr.rn = 1
ORDER BY cs.churn_rate_pct DESC;

-- 31. At-risk revenue report: composite SQL risk score x monthly_price, top 50.
WITH recency AS (
    SELECT customer_id,
           (CURRENT_DATE - MAX(viewing_date)) AS days_since_last_activity
    FROM viewing_activity
    GROUP BY customer_id
),
failed AS (
    SELECT customer_id,
           COUNT(*) FILTER (WHERE payment_status = 'Failed') AS failed_count,
           COUNT(*) AS total_count
    FROM payments
    GROUP BY customer_id
),
tickets AS (
    SELECT customer_id, COUNT(*) AS ticket_count
    FROM support_tickets
    GROUP BY customer_id
),
active AS (
    SELECT customer_id, plan_id, monthly_price
    FROM subscriptions
    WHERE subscription_status = 'Active'
)
SELECT a.customer_id,
       a.plan_id,
       a.monthly_price,
       COALESCE(r.days_since_last_activity, 365) AS days_since_last_activity,
       COALESCE(f.failed_count, 0) AS failed_payments,
       COALESCE(t.ticket_count, 0) AS support_tickets,
       ROUND(0.5 * LEAST(COALESCE(r.days_since_last_activity, 365) / 365.0, 1)
           + 0.3 * COALESCE(f.failed_count, 0) / 5.0
           + 0.2 * LEAST(COALESCE(t.ticket_count, 0) / 10.0, 1), 3) AS risk_score,
       ROUND(a.monthly_price * (0.5 * LEAST(COALESCE(r.days_since_last_activity, 365) / 365.0, 1)
           + 0.3 * COALESCE(f.failed_count, 0) / 5.0
           + 0.2 * LEAST(COALESCE(t.ticket_count, 0) / 10.0, 1)), 2) AS at_risk_revenue
FROM active a
LEFT JOIN recency r ON r.customer_id = a.customer_id
LEFT JOIN failed f ON f.customer_id = a.customer_id
LEFT JOIN tickets t ON t.customer_id = a.customer_id
ORDER BY at_risk_revenue DESC
LIMIT 50;

-- 32. Top 5 complaints per country, most recent completed quarter.
WITH recent_q AS (
    SELECT DATE_TRUNC('quarter', MAX(ticket_date))::date - INTERVAL '3 months' AS q_start
    FROM support_tickets
),
base AS (
    SELECT c.country,
           t.issue_subcategory,
           AVG(t.resolution_time_hours) AS avg_res_time,
           AVG(t.customer_satisfaction_score) AS avg_csat,
           COUNT(*) AS volume,
           ROW_NUMBER() OVER (PARTITION BY c.country ORDER BY COUNT(*) DESC) AS rn
    FROM support_tickets t
    JOIN customers c ON c.customer_id = t.customer_id
    CROSS JOIN recent_q rq
    WHERE t.ticket_date >= rq.q_start
      AND t.ticket_date < rq.q_start + INTERVAL '3 months'
    GROUP BY c.country, t.issue_subcategory
)
SELECT country,
       issue_subcategory,
       volume,
       ROUND(avg_res_time, 2) AS avg_resolution_hours,
       ROUND(avg_csat, 2) AS avg_satisfaction
FROM base
WHERE rn <= 5
ORDER BY country, volume DESC;

-- 33. Win-back candidates: churned customers with top-quartile CLV.
WITH spend AS (
    SELECT customer_id,
           SUM(amount) AS clv
    FROM payments
    WHERE payment_status = 'Success'
    GROUP BY customer_id
)
SELECT cl.customer_id,
       cl.churn_reason,
       s.clv,
       va.last_engagement
FROM churn_labels cl
JOIN spend s ON s.customer_id = cl.customer_id
LEFT JOIN (SELECT customer_id, MAX(viewing_date) AS last_engagement
           FROM viewing_activity GROUP BY customer_id) va ON va.customer_id = cl.customer_id
WHERE cl.churned
  AND s.clv >= (SELECT PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY clv) FROM spend)
ORDER BY s.clv DESC;

-- 34. Plan-migration analysis: most common paths + upgrader vs downgrader churn.
WITH mig AS (
    SELECT customer_id,
           plan_id,
           LAG(plan_id) OVER (PARTITION BY customer_id
                              ORDER BY subscription_start_date) AS prev_plan
    FROM subscriptions
),
paths AS (
    SELECT customer_id,
           prev_plan,
           plan_id AS new_plan,
           CASE WHEN prev_plan < plan_id THEN 'Upgrade' ELSE 'Downgrade' END AS direction
    FROM mig
    WHERE prev_plan IS NOT NULL AND prev_plan <> plan_id
)
SELECT prev_plan,
       new_plan,
       direction,
       COUNT(DISTINCT p.customer_id) AS customers,
       ROUND(100.0 * COUNT(DISTINCT CASE WHEN cl.churned THEN p.customer_id END)
             / COUNT(DISTINCT p.customer_id), 2) AS churn_rate_pct
FROM paths p
LEFT JOIN churn_labels cl ON cl.customer_id = p.customer_id
GROUP BY prev_plan, new_plan, direction
ORDER BY customers DESC;

-- 35. WAU / MAU trend over last 6 months + stickiness ratio.
WITH weeks AS (
    SELECT customer_id,
           DATE_TRUNC('week', viewing_date)::date AS week
    FROM viewing_activity
    WHERE viewing_date >= DATE_TRUNC('month', CURRENT_DATE) - INTERVAL '6 months'
    GROUP BY 1, 2
),
months AS (
    SELECT customer_id,
           DATE_TRUNC('month', viewing_date)::date AS month
    FROM viewing_activity
    WHERE viewing_date >= DATE_TRUNC('month', CURRENT_DATE) - INTERVAL '6 months'
    GROUP BY 1, 2
),
w AS (SELECT week, COUNT(*) AS wau FROM weeks GROUP BY week),
m AS (SELECT month, COUNT(*) AS mau FROM months GROUP BY month)
SELECT w.week,
       w.wau,
       m.mau,
       ROUND(100.0 * w.wau / m.mau, 2) AS stickiness_pct
FROM w
JOIN m ON DATE_TRUNC('month', w.week) = m.month
ORDER BY w.week;

-- 36. Negative feedback within 14 days of a failed payment or a CSAT<=2 ticket.
WITH neg_fb AS (
    SELECT customer_id, feedback_date, rating, feedback_text
    FROM customer_feedback
    WHERE rating <= 2
),
failed AS (
    SELECT customer_id, payment_date FROM payments WHERE payment_status = 'Failed'
),
bad_tickets AS (
    SELECT customer_id, ticket_date
    FROM support_tickets
    WHERE customer_satisfaction_score <= 2
)
SELECT DISTINCT nf.customer_id,
       nf.feedback_date,
       nf.rating,
       nf.feedback_text
FROM neg_fb nf
WHERE EXISTS (SELECT 1 FROM failed f
              WHERE f.customer_id = nf.customer_id
                AND ABS(f.payment_date - nf.feedback_date) <= 14)
   OR EXISTS (SELECT 1 FROM bad_tickets bt
              WHERE bt.customer_id = nf.customer_id
                AND ABS(bt.ticket_date - nf.feedback_date) <= 14);

-- 37. Full customer health score (0-100), ranked descending by risk.
WITH recency AS (
    SELECT customer_id,
           COALESCE((CURRENT_DATE - MAX(viewing_date)), 365) AS days_since
    FROM viewing_activity
    GROUP BY customer_id
),
pay AS (
    SELECT customer_id,
           COUNT(*) FILTER (WHERE payment_status = 'Failed') AS failed_count,
           COUNT(*) AS total_count
    FROM payments
    GROUP BY customer_id
),
sat AS (
    SELECT customer_id, AVG(customer_satisfaction_score) AS avg_csat
    FROM support_tickets
    WHERE customer_satisfaction_score IS NOT NULL
    GROUP BY customer_id
),
tenure AS (
    SELECT customer_id, (CURRENT_DATE - registration_date) AS tenure_days
    FROM customers
),
active AS (
    SELECT customer_id, plan_id FROM subscriptions WHERE subscription_status = 'Active'
)
SELECT a.customer_id,
       a.plan_id,
       COALESCE(r.days_since, 365) AS days_since_last_activity,
       COALESCE(p.failed_count, 0) AS failed_payments,
       ROUND(COALESCE(p.failed_count, 0) / NULLIF(p.total_count, 0), 3) AS failed_payment_rate,
       ROUND(COALESCE(s.avg_csat, 3), 2) AS avg_satisfaction,
       COALESCE(t.tenure_days, 0) AS tenure_days,
       ROUND(GREATEST(0, LEAST(100,
           100 * (1 - LEAST(COALESCE(r.days_since, 365) / 180.0, 1))   -- recency component
         - 40 * LEAST(COALESCE(p.failed_count, 0) / 5.0, 1)            -- payment-failure penalty
         + 10 * ((COALESCE(s.avg_csat, 3) - 1) / 4)                    -- satisfaction component
         + 15 * LEAST(COALESCE(t.tenure_days, 0) / 1095.0, 1)          -- tenure component
       )), 2) AS health_score
FROM active a
LEFT JOIN recency r ON r.customer_id = a.customer_id
LEFT JOIN pay p ON p.customer_id = a.customer_id
LEFT JOIN sat s ON s.customer_id = a.customer_id
LEFT JOIN tenure t ON t.customer_id = a.customer_id
ORDER BY health_score ASC;
